### ISSUE TITLE
Crash - Destroying gear on floor

### ISSUE THREAD

**Issue by aldrin233** [shindouj/ProximityProspectingPick#2]
Running on 64 bit Windows 10.0.19045.0 with 16267 MB RAM
Game Version: v1.19.8 (Stable)
10/3/2024 8:40:32 PM: Critical error occurred in the following mod: proximityprospectingpick@1.0.1
Loaded Mods: proximityprospectingpick@1.0.1, game@1.19.8, hudclock@3.4.0, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProximityProspectingPick.ObjectExtensions.IsPropickable(Block self) in E:\jeikobu__'s stuff\PROJECTS\ProximityProspectingPick\ProximityProspectingPick\ObjectExtensions.cs:line 19
   at ProximityProspectingPick.ProspectingPickPatch.ProbeBlockProximityMode(IWorldAccessor world, Entity byEntity, BlockSelection blockSel, Int32 radius) in E:\jeikobu__'s stuff\PROJECTS\ProximityProspectingPick\ProximityProspectingPick\ProspectingPickPatch.cs:line 41
   at ProximityProspectingPick.ProspectingPickPatch.OnBlockBrokenWith(ItemProspectingPick __instance, Boolean& __result, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in E:\jeikobu__'s stuff\PROJECTS\ProximityProspectingPick\ProximityProspectingPick\ProspectingPickPatch.cs:line 24
   at Vintagestory.GameContent.ItemProspectingPick.OnBlockBrokenWith_Patch1(ItemProspectingPick this, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1687
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 785
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 592
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 220
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 83
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1009
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 241
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by shindouj** [comment]
@aldrin233 Thank you for your report! This issue has now been fixed and released as v1.0.2.
